### PR TITLE
Fixed Issue with Skipping Boss Phase

### LINKED ISSUE #144: Boss Phase is Immediately Skipped
I just noticed that the boss phase in the test_level_1 is immediately skipped and enemies start spawning on top of the boss. This is probably an event ordering issue that checks whether the boss has been destroyed.

### PR DESCRIPTION
**Pull request by cdsupina**
- Boss phase was being skipped due to not clearing the event queue for the boss destroyed events
- I reworked how the events were generated and read

Fixed #144

### CODE REVIEW

File: crates/thetawave_interface/src/spawnable.rs [hunk 1]
```diff
@@ -72,6 +72,13 @@ pub enum MobType {
 }
 
 impl MobType {
+    pub fn is_boss(&self) -> bool {
+        match self {
+            MobType::Enemy(EnemyMobType::Repeater) => true,
```
Comment (varoonp123) [inline crates/thetawave_interface/src/spawnable.rs]: How is this different from `Query<BossComponent>`? *gulp*

Comment (cdsupina) [reply crates/thetawave_interface/src/spawnable.rs]: @LordDeatHunter pointed this out too. I'm going to change this.

**Review by varoonp123 — APPROVED** [review]

**Comment by varoonp123** [comment]
I actually can reproduce this CI error locally and it looks to be an internal rustc error that was introduced in the last couple of days of the nightly rustc channel. This fails on today's nightly release, but works with nightly-2023-12-16
